/**
 *
 *  Oauth2AccessTokens.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Oauth2AccessTokens.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::oauth_test;

const std::string Oauth2AccessTokens::Cols::_token = "\"token\"";
const std::string Oauth2AccessTokens::Cols::_client_id = "\"client_id\"";
const std::string Oauth2AccessTokens::Cols::_user_id = "\"user_id\"";
const std::string Oauth2AccessTokens::Cols::_scope = "\"scope\"";
const std::string Oauth2AccessTokens::Cols::_expires_at = "\"expires_at\"";
const std::string Oauth2AccessTokens::Cols::_revoked = "\"revoked\"";
const std::string Oauth2AccessTokens::primaryKeyName = "token";
const bool Oauth2AccessTokens::hasPrimaryKey = true;
const std::string Oauth2AccessTokens::tableName = "\"oauth2_access_tokens\"";

const std::vector<typename Oauth2AccessTokens::MetaData> Oauth2AccessTokens::metaData_={
{"token","std::string","character varying",100,0,1,1},
{"client_id","std::string","character varying",50,0,0,1},
{"user_id","std::string","character varying",50,0,0,0},
{"scope","std::string","text",0,0,0,0},
{"expires_at","int64_t","bigint",8,0,0,1},
{"revoked","bool","boolean",1,0,0,0}
};
const std::string &Oauth2AccessTokens::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Oauth2AccessTokens::Oauth2AccessTokens(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["token"].isNull())
        {
            token_=std::make_shared<std::string>(r["token"].as<std::string>());
        }
        if(!r["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(r["client_id"].as<std::string>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(r["user_id"].as<std::string>());
        }
        if(!r["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(r["scope"].as<std::string>());
        }
        if(!r["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>(r["expires_at"].as<int64_t>());
        }
        if(!r["revoked"].isNull())
        {
            revoked_=std::make_shared<bool>(r["revoked"].as<bool>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            token_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            clientId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            scope_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            expiresAt_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            revoked_=std::make_shared<bool>(r[index].as<bool>());
        }
    }

}

Oauth2AccessTokens::Oauth2AccessTokens(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            token_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            scope_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            revoked_=std::make_shared<bool>(pJson[pMasqueradingVector[5]].asBool());
        }
    }
}

Oauth2AccessTokens::Oauth2AccessTokens(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("token"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["token"].isNull())
        {
            token_=std::make_shared<std::string>(pJson["token"].asString());
        }
    }
    if(pJson.isMember("client_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson["client_id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("scope"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(pJson["scope"].asString());
        }
    }
    if(pJson.isMember("expires_at"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson["expires_at"].asInt64());
        }
    }
    if(pJson.isMember("revoked"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["revoked"].isNull())
        {
            revoked_=std::make_shared<bool>(pJson["revoked"].asBool());
        }
    }
}

void Oauth2AccessTokens::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            token_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            scope_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            revoked_=std::make_shared<bool>(pJson[pMasqueradingVector[5]].asBool());
        }
    }
}

void Oauth2AccessTokens::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("token"))
    {
        if(!pJson["token"].isNull())
        {
            token_=std::make_shared<std::string>(pJson["token"].asString());
        }
    }
    if(pJson.isMember("client_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson["client_id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("scope"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(pJson["scope"].asString());
        }
    }
    if(pJson.isMember("expires_at"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson["expires_at"].asInt64());
        }
    }
    if(pJson.isMember("revoked"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["revoked"].isNull())
        {
            revoked_=std::make_shared<bool>(pJson["revoked"].asBool());
        }
    }
}

const std::string &Oauth2AccessTokens::getValueOfToken() const noexcept
{
    static const std::string defaultValue = std::string();
    if(token_)
        return *token_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2AccessTokens::getToken() const noexcept
{
    return token_;
}
void Oauth2AccessTokens::setToken(const std::string &pToken) noexcept
{
    token_ = std::make_shared<std::string>(pToken);
    dirtyFlag_[0] = true;
}
void Oauth2AccessTokens::setToken(std::string &&pToken) noexcept
{
    token_ = std::make_shared<std::string>(std::move(pToken));
    dirtyFlag_[0] = true;
}
const typename Oauth2AccessTokens::PrimaryKeyType & Oauth2AccessTokens::getPrimaryKey() const
{
    assert(token_);
    return *token_;
}

const std::string &Oauth2AccessTokens::getValueOfClientId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(clientId_)
        return *clientId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2AccessTokens::getClientId() const noexcept
{
    return clientId_;
}
void Oauth2AccessTokens::setClientId(const std::string &pClientId) noexcept
{
    clientId_ = std::make_shared<std::string>(pClientId);
    dirtyFlag_[1] = true;
}
void Oauth2AccessTokens::setClientId(std::string &&pClientId) noexcept
{
    clientId_ = std::make_shared<std::string>(std::move(pClientId));
    dirtyFlag_[1] = true;
}

const std::string &Oauth2AccessTokens::getValueOfUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2AccessTokens::getUserId() const noexcept
{
    return userId_;
}
void Oauth2AccessTokens::setUserId(const std::string &pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(pUserId);
    dirtyFlag_[2] = true;
}
void Oauth2AccessTokens::setUserId(std::string &&pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(std::move(pUserId));
    dirtyFlag_[2] = true;
}
void Oauth2AccessTokens::setUserIdToNull() noexcept
{
    userId_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Oauth2AccessTokens::getValueOfScope() const noexcept
{
    static const std::string defaultValue = std::string();
    if(scope_)
        return *scope_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2AccessTokens::getScope() const noexcept
{
    return scope_;
}
void Oauth2AccessTokens::setScope(const std::string &pScope) noexcept
{
    scope_ = std::make_shared<std::string>(pScope);
    dirtyFlag_[3] = true;
}
void Oauth2AccessTokens::setScope(std::string &&pScope) noexcept
{
    scope_ = std::make_shared<std::string>(std::move(pScope));
    dirtyFlag_[3] = true;
}
void Oauth2AccessTokens::setScopeToNull() noexcept
{
    scope_.reset();
    dirtyFlag_[3] = true;
}

const int64_t &Oauth2AccessTokens::getValueOfExpiresAt() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(expiresAt_)
        return *expiresAt_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Oauth2AccessTokens::getExpiresAt() const noexcept
{
    return expiresAt_;
}
void Oauth2AccessTokens::setExpiresAt(const int64_t &pExpiresAt) noexcept
{
    expiresAt_ = std::make_shared<int64_t>(pExpiresAt);
    dirtyFlag_[4] = true;
}

const bool &Oauth2AccessTokens::getValueOfRevoked() const noexcept
{
    static const bool defaultValue = bool();
    if(revoked_)
        return *revoked_;
    return defaultValue;
}
const std::shared_ptr<bool> &Oauth2AccessTokens::getRevoked() const noexcept
{
    return revoked_;
}
void Oauth2AccessTokens::setRevoked(const bool &pRevoked) noexcept
{
    revoked_ = std::make_shared<bool>(pRevoked);
    dirtyFlag_[5] = true;
}
void Oauth2AccessTokens::setRevokedToNull() noexcept
{
    revoked_.reset();
    dirtyFlag_[5] = true;
}

void Oauth2AccessTokens::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Oauth2AccessTokens::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "token",
        "client_id",
        "user_id",
        "scope",
        "expires_at",
        "revoked"
    };
    return inCols;
}

void Oauth2AccessTokens::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getToken())
        {
            binder << getValueOfToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getClientId())
        {
            binder << getValueOfClientId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getScope())
        {
            binder << getValueOfScope();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getExpiresAt())
        {
            binder << getValueOfExpiresAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getRevoked())
        {
            binder << getValueOfRevoked();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Oauth2AccessTokens::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void Oauth2AccessTokens::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getToken())
        {
            binder << getValueOfToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getClientId())
        {
            binder << getValueOfClientId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getScope())
        {
            binder << getValueOfScope();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getExpiresAt())
        {
            binder << getValueOfExpiresAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getRevoked())
        {
            binder << getValueOfRevoked();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Oauth2AccessTokens::toJson() const
{
    Json::Value ret;
    if(getToken())
    {
        ret["token"]=getValueOfToken();
    }
    else
    {
        ret["token"]=Json::Value();
    }
    if(getClientId())
    {
        ret["client_id"]=getValueOfClientId();
    }
    else
    {
        ret["client_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getScope())
    {
        ret["scope"]=getValueOfScope();
    }
    else
    {
        ret["scope"]=Json::Value();
    }
    if(getExpiresAt())
    {
        ret["expires_at"]=(Json::Int64)getValueOfExpiresAt();
    }
    else
    {
        ret["expires_at"]=Json::Value();
    }
    if(getRevoked())
    {
        ret["revoked"]=getValueOfRevoked();
    }
    else
    {
        ret["revoked"]=Json::Value();
    }
    return ret;
}

std::string Oauth2AccessTokens::toString() const
{
    return toJson().toStyledString();
}

Json::Value Oauth2AccessTokens::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getToken())
            {
                ret[pMasqueradingVector[0]]=getValueOfToken();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getClientId())
            {
                ret[pMasqueradingVector[1]]=getValueOfClientId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[2]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getScope())
            {
                ret[pMasqueradingVector[3]]=getValueOfScope();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getExpiresAt())
            {
                ret[pMasqueradingVector[4]]=(Json::Int64)getValueOfExpiresAt();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getRevoked())
            {
                ret[pMasqueradingVector[5]]=getValueOfRevoked();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getToken())
    {
        ret["token"]=getValueOfToken();
    }
    else
    {
        ret["token"]=Json::Value();
    }
    if(getClientId())
    {
        ret["client_id"]=getValueOfClientId();
    }
    else
    {
        ret["client_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getScope())
    {
        ret["scope"]=getValueOfScope();
    }
    else
    {
        ret["scope"]=Json::Value();
    }
    if(getExpiresAt())
    {
        ret["expires_at"]=(Json::Int64)getValueOfExpiresAt();
    }
    else
    {
        ret["expires_at"]=Json::Value();
    }
    if(getRevoked())
    {
        ret["revoked"]=getValueOfRevoked();
    }
    else
    {
        ret["revoked"]=Json::Value();
    }
    return ret;
}

bool Oauth2AccessTokens::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("token"))
    {
        if(!validJsonOfField(0, "token", pJson["token"], err, true))
            return false;
    }
    else
    {
        err="The token column cannot be null";
        return false;
    }
    if(pJson.isMember("client_id"))
    {
        if(!validJsonOfField(1, "client_id", pJson["client_id"], err, true))
            return false;
    }
    else
    {
        err="The client_id column cannot be null";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(2, "user_id", pJson["user_id"], err, true))
            return false;
    }
    if(pJson.isMember("scope"))
    {
        if(!validJsonOfField(3, "scope", pJson["scope"], err, true))
            return false;
    }
    if(pJson.isMember("expires_at"))
    {
        if(!validJsonOfField(4, "expires_at", pJson["expires_at"], err, true))
            return false;
    }
    else
    {
        err="The expires_at column cannot be null";
        return false;
    }
    if(pJson.isMember("revoked"))
    {
        if(!validJsonOfField(5, "revoked", pJson["revoked"], err, true))
            return false;
    }
    return true;
}
bool Oauth2AccessTokens::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                            const std::vector<std::string> &pMasqueradingVector,
                                                            std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Oauth2AccessTokens::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("token"))
    {
        if(!validJsonOfField(0, "token", pJson["token"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("client_id"))
    {
        if(!validJsonOfField(1, "client_id", pJson["client_id"], err, false))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(2, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("scope"))
    {
        if(!validJsonOfField(3, "scope", pJson["scope"], err, false))
            return false;
    }
    if(pJson.isMember("expires_at"))
    {
        if(!validJsonOfField(4, "expires_at", pJson["expires_at"], err, false))
            return false;
    }
    if(pJson.isMember("revoked"))
    {
        if(!validJsonOfField(5, "revoked", pJson["revoked"], err, false))
            return false;
    }
    return true;
}
bool Oauth2AccessTokens::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                          const std::vector<std::string> &pMasqueradingVector,
                                                          std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Oauth2AccessTokens::validJsonOfField(size_t index,
                                          const std::string &fieldName,
                                          const Json::Value &pJson,
                                          std::string &err,
                                          bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
