/**
 *
 *  Oauth2DeviceCodes.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Oauth2DeviceCodes.h"
#include "Oauth2Clients.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::oauth2_db;

const std::string Oauth2DeviceCodes::Cols::_device_code_hash = "\"device_code_hash\"";
const std::string Oauth2DeviceCodes::Cols::_user_code = "\"user_code\"";
const std::string Oauth2DeviceCodes::Cols::_client_id = "\"client_id\"";
const std::string Oauth2DeviceCodes::Cols::_scope = "\"scope\"";
const std::string Oauth2DeviceCodes::Cols::_status = "\"status\"";
const std::string Oauth2DeviceCodes::Cols::_user_id = "\"user_id\"";
const std::string Oauth2DeviceCodes::Cols::_expires_at = "\"expires_at\"";
const std::string Oauth2DeviceCodes::Cols::_interval_seconds = "\"interval_seconds\"";
const std::string Oauth2DeviceCodes::Cols::_last_polled_at = "\"last_polled_at\"";
const std::string Oauth2DeviceCodes::Cols::_created_at = "\"created_at\"";
const std::string Oauth2DeviceCodes::primaryKeyName = "device_code_hash";
const bool Oauth2DeviceCodes::hasPrimaryKey = true;
const std::string Oauth2DeviceCodes::tableName = "\"oauth2_device_codes\"";

const std::vector<typename Oauth2DeviceCodes::MetaData> Oauth2DeviceCodes::metaData_={
{"device_code_hash","std::string","character varying",64,0,1,1},
{"user_code","std::string","character varying",8,0,0,1},
{"client_id","std::string","character varying",50,0,0,1},
{"scope","std::string","text",0,0,0,0},
{"status","std::string","character varying",20,0,0,0},
{"user_id","std::string","character varying",50,0,0,0},
{"expires_at","int64_t","bigint",8,0,0,1},
{"interval_seconds","int32_t","integer",4,0,0,0},
{"last_polled_at","int64_t","bigint",8,0,0,0},
{"created_at","::trantor::Date","timestamp without time zone",0,0,0,0}
};
const std::string &Oauth2DeviceCodes::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Oauth2DeviceCodes::Oauth2DeviceCodes(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["device_code_hash"].isNull())
        {
            deviceCodeHash_=std::make_shared<std::string>(r["device_code_hash"].as<std::string>());
        }
        if(!r["user_code"].isNull())
        {
            userCode_=std::make_shared<std::string>(r["user_code"].as<std::string>());
        }
        if(!r["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(r["client_id"].as<std::string>());
        }
        if(!r["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(r["scope"].as<std::string>());
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(r["user_id"].as<std::string>());
        }
        if(!r["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>(r["expires_at"].as<int64_t>());
        }
        if(!r["interval_seconds"].isNull())
        {
            intervalSeconds_=std::make_shared<int32_t>(r["interval_seconds"].as<int32_t>());
        }
        if(!r["last_polled_at"].isNull())
        {
            lastPolledAt_=std::make_shared<int64_t>(r["last_polled_at"].as<int64_t>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 10 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            deviceCodeHash_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            userCode_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            clientId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            scope_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            expiresAt_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            intervalSeconds_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            lastPolledAt_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

Oauth2DeviceCodes::Oauth2DeviceCodes(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            deviceCodeHash_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            scope_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            intervalSeconds_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            lastPolledAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

Oauth2DeviceCodes::Oauth2DeviceCodes(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("device_code_hash"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["device_code_hash"].isNull())
        {
            deviceCodeHash_=std::make_shared<std::string>(pJson["device_code_hash"].asString());
        }
    }
    if(pJson.isMember("user_code"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["user_code"].isNull())
        {
            userCode_=std::make_shared<std::string>(pJson["user_code"].asString());
        }
    }
    if(pJson.isMember("client_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson["client_id"].asString());
        }
    }
    if(pJson.isMember("scope"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(pJson["scope"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("expires_at"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson["expires_at"].asInt64());
        }
    }
    if(pJson.isMember("interval_seconds"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["interval_seconds"].isNull())
        {
            intervalSeconds_=std::make_shared<int32_t>((int32_t)pJson["interval_seconds"].asInt64());
        }
    }
    if(pJson.isMember("last_polled_at"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["last_polled_at"].isNull())
        {
            lastPolledAt_=std::make_shared<int64_t>((int64_t)pJson["last_polled_at"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Oauth2DeviceCodes::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 10)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            deviceCodeHash_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            userCode_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            scope_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            intervalSeconds_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            lastPolledAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[8]].asInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[9]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void Oauth2DeviceCodes::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("device_code_hash"))
    {
        if(!pJson["device_code_hash"].isNull())
        {
            deviceCodeHash_=std::make_shared<std::string>(pJson["device_code_hash"].asString());
        }
    }
    if(pJson.isMember("user_code"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["user_code"].isNull())
        {
            userCode_=std::make_shared<std::string>(pJson["user_code"].asString());
        }
    }
    if(pJson.isMember("client_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson["client_id"].asString());
        }
    }
    if(pJson.isMember("scope"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(pJson["scope"].asString());
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("expires_at"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson["expires_at"].asInt64());
        }
    }
    if(pJson.isMember("interval_seconds"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["interval_seconds"].isNull())
        {
            intervalSeconds_=std::make_shared<int32_t>((int32_t)pJson["interval_seconds"].asInt64());
        }
    }
    if(pJson.isMember("last_polled_at"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["last_polled_at"].isNull())
        {
            lastPolledAt_=std::make_shared<int64_t>((int64_t)pJson["last_polled_at"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const std::string &Oauth2DeviceCodes::getValueOfDeviceCodeHash() const noexcept
{
    static const std::string defaultValue = std::string();
    if(deviceCodeHash_)
        return *deviceCodeHash_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2DeviceCodes::getDeviceCodeHash() const noexcept
{
    return deviceCodeHash_;
}
void Oauth2DeviceCodes::setDeviceCodeHash(const std::string &pDeviceCodeHash) noexcept
{
    deviceCodeHash_ = std::make_shared<std::string>(pDeviceCodeHash);
    dirtyFlag_[0] = true;
}
void Oauth2DeviceCodes::setDeviceCodeHash(std::string &&pDeviceCodeHash) noexcept
{
    deviceCodeHash_ = std::make_shared<std::string>(std::move(pDeviceCodeHash));
    dirtyFlag_[0] = true;
}
const typename Oauth2DeviceCodes::PrimaryKeyType & Oauth2DeviceCodes::getPrimaryKey() const
{
    assert(deviceCodeHash_);
    return *deviceCodeHash_;
}

const std::string &Oauth2DeviceCodes::getValueOfUserCode() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userCode_)
        return *userCode_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2DeviceCodes::getUserCode() const noexcept
{
    return userCode_;
}
void Oauth2DeviceCodes::setUserCode(const std::string &pUserCode) noexcept
{
    userCode_ = std::make_shared<std::string>(pUserCode);
    dirtyFlag_[1] = true;
}
void Oauth2DeviceCodes::setUserCode(std::string &&pUserCode) noexcept
{
    userCode_ = std::make_shared<std::string>(std::move(pUserCode));
    dirtyFlag_[1] = true;
}

const std::string &Oauth2DeviceCodes::getValueOfClientId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(clientId_)
        return *clientId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2DeviceCodes::getClientId() const noexcept
{
    return clientId_;
}
void Oauth2DeviceCodes::setClientId(const std::string &pClientId) noexcept
{
    clientId_ = std::make_shared<std::string>(pClientId);
    dirtyFlag_[2] = true;
}
void Oauth2DeviceCodes::setClientId(std::string &&pClientId) noexcept
{
    clientId_ = std::make_shared<std::string>(std::move(pClientId));
    dirtyFlag_[2] = true;
}

const std::string &Oauth2DeviceCodes::getValueOfScope() const noexcept
{
    static const std::string defaultValue = std::string();
    if(scope_)
        return *scope_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2DeviceCodes::getScope() const noexcept
{
    return scope_;
}
void Oauth2DeviceCodes::setScope(const std::string &pScope) noexcept
{
    scope_ = std::make_shared<std::string>(pScope);
    dirtyFlag_[3] = true;
}
void Oauth2DeviceCodes::setScope(std::string &&pScope) noexcept
{
    scope_ = std::make_shared<std::string>(std::move(pScope));
    dirtyFlag_[3] = true;
}
void Oauth2DeviceCodes::setScopeToNull() noexcept
{
    scope_.reset();
    dirtyFlag_[3] = true;
}

const std::string &Oauth2DeviceCodes::getValueOfStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2DeviceCodes::getStatus() const noexcept
{
    return status_;
}
void Oauth2DeviceCodes::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[4] = true;
}
void Oauth2DeviceCodes::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[4] = true;
}
void Oauth2DeviceCodes::setStatusToNull() noexcept
{
    status_.reset();
    dirtyFlag_[4] = true;
}

const std::string &Oauth2DeviceCodes::getValueOfUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2DeviceCodes::getUserId() const noexcept
{
    return userId_;
}
void Oauth2DeviceCodes::setUserId(const std::string &pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(pUserId);
    dirtyFlag_[5] = true;
}
void Oauth2DeviceCodes::setUserId(std::string &&pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(std::move(pUserId));
    dirtyFlag_[5] = true;
}
void Oauth2DeviceCodes::setUserIdToNull() noexcept
{
    userId_.reset();
    dirtyFlag_[5] = true;
}

const int64_t &Oauth2DeviceCodes::getValueOfExpiresAt() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(expiresAt_)
        return *expiresAt_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Oauth2DeviceCodes::getExpiresAt() const noexcept
{
    return expiresAt_;
}
void Oauth2DeviceCodes::setExpiresAt(const int64_t &pExpiresAt) noexcept
{
    expiresAt_ = std::make_shared<int64_t>(pExpiresAt);
    dirtyFlag_[6] = true;
}

const int32_t &Oauth2DeviceCodes::getValueOfIntervalSeconds() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(intervalSeconds_)
        return *intervalSeconds_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Oauth2DeviceCodes::getIntervalSeconds() const noexcept
{
    return intervalSeconds_;
}
void Oauth2DeviceCodes::setIntervalSeconds(const int32_t &pIntervalSeconds) noexcept
{
    intervalSeconds_ = std::make_shared<int32_t>(pIntervalSeconds);
    dirtyFlag_[7] = true;
}
void Oauth2DeviceCodes::setIntervalSecondsToNull() noexcept
{
    intervalSeconds_.reset();
    dirtyFlag_[7] = true;
}

const int64_t &Oauth2DeviceCodes::getValueOfLastPolledAt() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(lastPolledAt_)
        return *lastPolledAt_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Oauth2DeviceCodes::getLastPolledAt() const noexcept
{
    return lastPolledAt_;
}
void Oauth2DeviceCodes::setLastPolledAt(const int64_t &pLastPolledAt) noexcept
{
    lastPolledAt_ = std::make_shared<int64_t>(pLastPolledAt);
    dirtyFlag_[8] = true;
}
void Oauth2DeviceCodes::setLastPolledAtToNull() noexcept
{
    lastPolledAt_.reset();
    dirtyFlag_[8] = true;
}

const ::trantor::Date &Oauth2DeviceCodes::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Oauth2DeviceCodes::getCreatedAt() const noexcept
{
    return createdAt_;
}
void Oauth2DeviceCodes::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[9] = true;
}
void Oauth2DeviceCodes::setCreatedAtToNull() noexcept
{
    createdAt_.reset();
    dirtyFlag_[9] = true;
}

void Oauth2DeviceCodes::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Oauth2DeviceCodes::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "device_code_hash",
        "user_code",
        "client_id",
        "scope",
        "status",
        "user_id",
        "expires_at",
        "interval_seconds",
        "last_polled_at",
        "created_at"
    };
    return inCols;
}

void Oauth2DeviceCodes::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getDeviceCodeHash())
        {
            binder << getValueOfDeviceCodeHash();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserCode())
        {
            binder << getValueOfUserCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getClientId())
        {
            binder << getValueOfClientId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getScope())
        {
            binder << getValueOfScope();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getExpiresAt())
        {
            binder << getValueOfExpiresAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getIntervalSeconds())
        {
            binder << getValueOfIntervalSeconds();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getLastPolledAt())
        {
            binder << getValueOfLastPolledAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Oauth2DeviceCodes::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    return ret;
}

void Oauth2DeviceCodes::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getDeviceCodeHash())
        {
            binder << getValueOfDeviceCodeHash();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getUserCode())
        {
            binder << getValueOfUserCode();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getClientId())
        {
            binder << getValueOfClientId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getScope())
        {
            binder << getValueOfScope();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getExpiresAt())
        {
            binder << getValueOfExpiresAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getIntervalSeconds())
        {
            binder << getValueOfIntervalSeconds();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getLastPolledAt())
        {
            binder << getValueOfLastPolledAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Oauth2DeviceCodes::toJson() const
{
    Json::Value ret;
    if(getDeviceCodeHash())
    {
        ret["device_code_hash"]=getValueOfDeviceCodeHash();
    }
    else
    {
        ret["device_code_hash"]=Json::Value();
    }
    if(getUserCode())
    {
        ret["user_code"]=getValueOfUserCode();
    }
    else
    {
        ret["user_code"]=Json::Value();
    }
    if(getClientId())
    {
        ret["client_id"]=getValueOfClientId();
    }
    else
    {
        ret["client_id"]=Json::Value();
    }
    if(getScope())
    {
        ret["scope"]=getValueOfScope();
    }
    else
    {
        ret["scope"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getExpiresAt())
    {
        ret["expires_at"]=(Json::Int64)getValueOfExpiresAt();
    }
    else
    {
        ret["expires_at"]=Json::Value();
    }
    if(getIntervalSeconds())
    {
        ret["interval_seconds"]=getValueOfIntervalSeconds();
    }
    else
    {
        ret["interval_seconds"]=Json::Value();
    }
    if(getLastPolledAt())
    {
        ret["last_polled_at"]=(Json::Int64)getValueOfLastPolledAt();
    }
    else
    {
        ret["last_polled_at"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

std::string Oauth2DeviceCodes::toString() const
{
    return toJson().toStyledString();
}

Json::Value Oauth2DeviceCodes::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 10)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getDeviceCodeHash())
            {
                ret[pMasqueradingVector[0]]=getValueOfDeviceCodeHash();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUserCode())
            {
                ret[pMasqueradingVector[1]]=getValueOfUserCode();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getClientId())
            {
                ret[pMasqueradingVector[2]]=getValueOfClientId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getScope())
            {
                ret[pMasqueradingVector[3]]=getValueOfScope();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[4]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[5]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getExpiresAt())
            {
                ret[pMasqueradingVector[6]]=(Json::Int64)getValueOfExpiresAt();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getIntervalSeconds())
            {
                ret[pMasqueradingVector[7]]=getValueOfIntervalSeconds();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getLastPolledAt())
            {
                ret[pMasqueradingVector[8]]=(Json::Int64)getValueOfLastPolledAt();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[9]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getDeviceCodeHash())
    {
        ret["device_code_hash"]=getValueOfDeviceCodeHash();
    }
    else
    {
        ret["device_code_hash"]=Json::Value();
    }
    if(getUserCode())
    {
        ret["user_code"]=getValueOfUserCode();
    }
    else
    {
        ret["user_code"]=Json::Value();
    }
    if(getClientId())
    {
        ret["client_id"]=getValueOfClientId();
    }
    else
    {
        ret["client_id"]=Json::Value();
    }
    if(getScope())
    {
        ret["scope"]=getValueOfScope();
    }
    else
    {
        ret["scope"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getExpiresAt())
    {
        ret["expires_at"]=(Json::Int64)getValueOfExpiresAt();
    }
    else
    {
        ret["expires_at"]=Json::Value();
    }
    if(getIntervalSeconds())
    {
        ret["interval_seconds"]=getValueOfIntervalSeconds();
    }
    else
    {
        ret["interval_seconds"]=Json::Value();
    }
    if(getLastPolledAt())
    {
        ret["last_polled_at"]=(Json::Int64)getValueOfLastPolledAt();
    }
    else
    {
        ret["last_polled_at"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    return ret;
}

bool Oauth2DeviceCodes::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("device_code_hash"))
    {
        if(!validJsonOfField(0, "device_code_hash", pJson["device_code_hash"], err, true))
            return false;
    }
    else
    {
        err="The device_code_hash column cannot be null";
        return false;
    }
    if(pJson.isMember("user_code"))
    {
        if(!validJsonOfField(1, "user_code", pJson["user_code"], err, true))
            return false;
    }
    else
    {
        err="The user_code column cannot be null";
        return false;
    }
    if(pJson.isMember("client_id"))
    {
        if(!validJsonOfField(2, "client_id", pJson["client_id"], err, true))
            return false;
    }
    else
    {
        err="The client_id column cannot be null";
        return false;
    }
    if(pJson.isMember("scope"))
    {
        if(!validJsonOfField(3, "scope", pJson["scope"], err, true))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(4, "status", pJson["status"], err, true))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(5, "user_id", pJson["user_id"], err, true))
            return false;
    }
    if(pJson.isMember("expires_at"))
    {
        if(!validJsonOfField(6, "expires_at", pJson["expires_at"], err, true))
            return false;
    }
    else
    {
        err="The expires_at column cannot be null";
        return false;
    }
    if(pJson.isMember("interval_seconds"))
    {
        if(!validJsonOfField(7, "interval_seconds", pJson["interval_seconds"], err, true))
            return false;
    }
    if(pJson.isMember("last_polled_at"))
    {
        if(!validJsonOfField(8, "last_polled_at", pJson["last_polled_at"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(9, "created_at", pJson["created_at"], err, true))
            return false;
    }
    return true;
}
bool Oauth2DeviceCodes::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[6] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Oauth2DeviceCodes::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("device_code_hash"))
    {
        if(!validJsonOfField(0, "device_code_hash", pJson["device_code_hash"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("user_code"))
    {
        if(!validJsonOfField(1, "user_code", pJson["user_code"], err, false))
            return false;
    }
    if(pJson.isMember("client_id"))
    {
        if(!validJsonOfField(2, "client_id", pJson["client_id"], err, false))
            return false;
    }
    if(pJson.isMember("scope"))
    {
        if(!validJsonOfField(3, "scope", pJson["scope"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(4, "status", pJson["status"], err, false))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(5, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("expires_at"))
    {
        if(!validJsonOfField(6, "expires_at", pJson["expires_at"], err, false))
            return false;
    }
    if(pJson.isMember("interval_seconds"))
    {
        if(!validJsonOfField(7, "interval_seconds", pJson["interval_seconds"], err, false))
            return false;
    }
    if(pJson.isMember("last_polled_at"))
    {
        if(!validJsonOfField(8, "last_polled_at", pJson["last_polled_at"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(9, "created_at", pJson["created_at"], err, false))
            return false;
    }
    return true;
}
bool Oauth2DeviceCodes::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                         const std::vector<std::string> &pMasqueradingVector,
                                                         std::string &err)
{
    if(pMasqueradingVector.size() != 10)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Oauth2DeviceCodes::validJsonOfField(size_t index,
                                         const std::string &fieldName,
                                         const Json::Value &pJson,
                                         std::string &err,
                                         bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 8)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 8)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Oauth2Clients Oauth2DeviceCodes::getOauth2Clients(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from oauth2_clients where client_id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *clientId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Oauth2Clients(r[0]);
}

void Oauth2DeviceCodes::getOauth2Clients(const DbClientPtr &clientPtr,
                                         const std::function<void(Oauth2Clients)> &rcb,
                                         const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from oauth2_clients where client_id = $1";
    *clientPtr << sql
               << *clientId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Oauth2Clients(r[0]));
                    }
               }
               >> ecb;
}
