/**
 *
 *  Oauth2ClientScopes.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Oauth2ClientScopes.h"
#include "Oauth2Clients.h"
#include "Oauth2Scopes.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::oauth2_db;

const std::string Oauth2ClientScopes::Cols::_id = "\"id\"";
const std::string Oauth2ClientScopes::Cols::_client_id = "\"client_id\"";
const std::string Oauth2ClientScopes::Cols::_scope_name = "\"scope_name\"";
const std::string Oauth2ClientScopes::primaryKeyName = "id";
const bool Oauth2ClientScopes::hasPrimaryKey = true;
const std::string Oauth2ClientScopes::tableName = "\"oauth2_client_scopes\"";

const std::vector<typename Oauth2ClientScopes::MetaData> Oauth2ClientScopes::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"client_id","std::string","character varying",50,0,0,0},
{"scope_name","std::string","character varying",100,0,0,0}
};
const std::string &Oauth2ClientScopes::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Oauth2ClientScopes::Oauth2ClientScopes(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(r["client_id"].as<std::string>());
        }
        if(!r["scope_name"].isNull())
        {
            scopeName_=std::make_shared<std::string>(r["scope_name"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            clientId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            scopeName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

Oauth2ClientScopes::Oauth2ClientScopes(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            scopeName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

Oauth2ClientScopes::Oauth2ClientScopes(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("client_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson["client_id"].asString());
        }
    }
    if(pJson.isMember("scope_name"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["scope_name"].isNull())
        {
            scopeName_=std::make_shared<std::string>(pJson["scope_name"].asString());
        }
    }
}

void Oauth2ClientScopes::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            scopeName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

void Oauth2ClientScopes::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("client_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson["client_id"].asString());
        }
    }
    if(pJson.isMember("scope_name"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["scope_name"].isNull())
        {
            scopeName_=std::make_shared<std::string>(pJson["scope_name"].asString());
        }
    }
}

const int32_t &Oauth2ClientScopes::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Oauth2ClientScopes::getId() const noexcept
{
    return id_;
}
void Oauth2ClientScopes::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Oauth2ClientScopes::PrimaryKeyType & Oauth2ClientScopes::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Oauth2ClientScopes::getValueOfClientId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(clientId_)
        return *clientId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2ClientScopes::getClientId() const noexcept
{
    return clientId_;
}
void Oauth2ClientScopes::setClientId(const std::string &pClientId) noexcept
{
    clientId_ = std::make_shared<std::string>(pClientId);
    dirtyFlag_[1] = true;
}
void Oauth2ClientScopes::setClientId(std::string &&pClientId) noexcept
{
    clientId_ = std::make_shared<std::string>(std::move(pClientId));
    dirtyFlag_[1] = true;
}
void Oauth2ClientScopes::setClientIdToNull() noexcept
{
    clientId_.reset();
    dirtyFlag_[1] = true;
}

const std::string &Oauth2ClientScopes::getValueOfScopeName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(scopeName_)
        return *scopeName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2ClientScopes::getScopeName() const noexcept
{
    return scopeName_;
}
void Oauth2ClientScopes::setScopeName(const std::string &pScopeName) noexcept
{
    scopeName_ = std::make_shared<std::string>(pScopeName);
    dirtyFlag_[2] = true;
}
void Oauth2ClientScopes::setScopeName(std::string &&pScopeName) noexcept
{
    scopeName_ = std::make_shared<std::string>(std::move(pScopeName));
    dirtyFlag_[2] = true;
}
void Oauth2ClientScopes::setScopeNameToNull() noexcept
{
    scopeName_.reset();
    dirtyFlag_[2] = true;
}

void Oauth2ClientScopes::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Oauth2ClientScopes::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "client_id",
        "scope_name"
    };
    return inCols;
}

void Oauth2ClientScopes::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getClientId())
        {
            binder << getValueOfClientId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getScopeName())
        {
            binder << getValueOfScopeName();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Oauth2ClientScopes::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void Oauth2ClientScopes::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getClientId())
        {
            binder << getValueOfClientId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getScopeName())
        {
            binder << getValueOfScopeName();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Oauth2ClientScopes::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getClientId())
    {
        ret["client_id"]=getValueOfClientId();
    }
    else
    {
        ret["client_id"]=Json::Value();
    }
    if(getScopeName())
    {
        ret["scope_name"]=getValueOfScopeName();
    }
    else
    {
        ret["scope_name"]=Json::Value();
    }
    return ret;
}

std::string Oauth2ClientScopes::toString() const
{
    return toJson().toStyledString();
}

Json::Value Oauth2ClientScopes::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getClientId())
            {
                ret[pMasqueradingVector[1]]=getValueOfClientId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getScopeName())
            {
                ret[pMasqueradingVector[2]]=getValueOfScopeName();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getClientId())
    {
        ret["client_id"]=getValueOfClientId();
    }
    else
    {
        ret["client_id"]=Json::Value();
    }
    if(getScopeName())
    {
        ret["scope_name"]=getValueOfScopeName();
    }
    else
    {
        ret["scope_name"]=Json::Value();
    }
    return ret;
}

bool Oauth2ClientScopes::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("client_id"))
    {
        if(!validJsonOfField(1, "client_id", pJson["client_id"], err, true))
            return false;
    }
    if(pJson.isMember("scope_name"))
    {
        if(!validJsonOfField(2, "scope_name", pJson["scope_name"], err, true))
            return false;
    }
    return true;
}
bool Oauth2ClientScopes::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                            const std::vector<std::string> &pMasqueradingVector,
                                                            std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Oauth2ClientScopes::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("client_id"))
    {
        if(!validJsonOfField(1, "client_id", pJson["client_id"], err, false))
            return false;
    }
    if(pJson.isMember("scope_name"))
    {
        if(!validJsonOfField(2, "scope_name", pJson["scope_name"], err, false))
            return false;
    }
    return true;
}
bool Oauth2ClientScopes::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                          const std::vector<std::string> &pMasqueradingVector,
                                                          std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Oauth2ClientScopes::validJsonOfField(size_t index,
                                          const std::string &fieldName,
                                          const Json::Value &pJson,
                                          std::string &err,
                                          bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Oauth2Clients Oauth2ClientScopes::getOauth2Clients(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from oauth2_clients where client_id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *clientId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Oauth2Clients(r[0]);
}

void Oauth2ClientScopes::getOauth2Clients(const DbClientPtr &clientPtr,
                                          const std::function<void(Oauth2Clients)> &rcb,
                                          const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from oauth2_clients where client_id = $1";
    *clientPtr << sql
               << *clientId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Oauth2Clients(r[0]));
                    }
               }
               >> ecb;
}
Oauth2Scopes Oauth2ClientScopes::getOauth2Scopes(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from oauth2_scopes where name = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *scopeName_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Oauth2Scopes(r[0]);
}

void Oauth2ClientScopes::getOauth2Scopes(const DbClientPtr &clientPtr,
                                         const std::function<void(Oauth2Scopes)> &rcb,
                                         const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from oauth2_scopes where name = $1";
    *clientPtr << sql
               << *scopeName_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Oauth2Scopes(r[0]));
                    }
               }
               >> ecb;
}
