/**
 *
 *  Users.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Users.h"
#include "Oauth2AccessTokens.h"
#include "Oauth2SubjectMappings.h"
#include "Oauth2UserConsents.h"
#include "Organizations.h"
#include "Roles.h"
#include "UserRoles.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::oauth2_db;

const std::string Users::Cols::_id = "\"id\"";
const std::string Users::Cols::_username = "\"username\"";
const std::string Users::Cols::_password_hash = "\"password_hash\"";
const std::string Users::Cols::_salt = "\"salt\"";
const std::string Users::Cols::_email = "\"email\"";
const std::string Users::Cols::_created_at = "\"created_at\"";
const std::string Users::Cols::_public_sub = "\"public_sub\"";
const std::string Users::Cols::_email_verified = "\"email_verified\"";
const std::string Users::Cols::_mfa_enabled = "\"mfa_enabled\"";
const std::string Users::Cols::_mfa_secret = "\"mfa_secret\"";
const std::string Users::Cols::_mfa_backup_codes = "\"mfa_backup_codes\"";
const std::string Users::Cols::_failed_login_count = "\"failed_login_count\"";
const std::string Users::Cols::_locked_until = "\"locked_until\"";
const std::string Users::Cols::_last_failed_login = "\"last_failed_login\"";
const std::string Users::Cols::_org_id = "\"org_id\"";
const std::string Users::primaryKeyName = "id";
const bool Users::hasPrimaryKey = true;
const std::string Users::tableName = "\"users\"";

const std::vector<typename Users::MetaData> Users::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"username","std::string","character varying",50,0,0,1},
{"password_hash","std::string","character varying",256,0,0,1},
{"salt","std::string","character varying",36,0,0,1},
{"email","std::string","character varying",100,0,0,0},
{"created_at","::trantor::Date","timestamp without time zone",0,0,0,0},
{"public_sub","std::string","uuid",0,0,0,1},
{"email_verified","bool","boolean",1,0,0,0},
{"mfa_enabled","bool","boolean",1,0,0,0},
{"mfa_secret","std::string","character varying",64,0,0,0},
{"mfa_backup_codes","std::string","text",0,0,0,0},
{"failed_login_count","int32_t","integer",4,0,0,0},
{"locked_until","int64_t","bigint",8,0,0,0},
{"last_failed_login","int64_t","bigint",8,0,0,0},
{"org_id","int32_t","integer",4,0,0,0}
};
const std::string &Users::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Users::Users(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["username"].isNull())
        {
            username_=std::make_shared<std::string>(r["username"].as<std::string>());
        }
        if(!r["password_hash"].isNull())
        {
            passwordHash_=std::make_shared<std::string>(r["password_hash"].as<std::string>());
        }
        if(!r["salt"].isNull())
        {
            salt_=std::make_shared<std::string>(r["salt"].as<std::string>());
        }
        if(!r["email"].isNull())
        {
            email_=std::make_shared<std::string>(r["email"].as<std::string>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["public_sub"].isNull())
        {
            publicSub_=std::make_shared<std::string>(r["public_sub"].as<std::string>());
        }
        if(!r["email_verified"].isNull())
        {
            emailVerified_=std::make_shared<bool>(r["email_verified"].as<bool>());
        }
        if(!r["mfa_enabled"].isNull())
        {
            mfaEnabled_=std::make_shared<bool>(r["mfa_enabled"].as<bool>());
        }
        if(!r["mfa_secret"].isNull())
        {
            mfaSecret_=std::make_shared<std::string>(r["mfa_secret"].as<std::string>());
        }
        if(!r["mfa_backup_codes"].isNull())
        {
            mfaBackupCodes_=std::make_shared<std::string>(r["mfa_backup_codes"].as<std::string>());
        }
        if(!r["failed_login_count"].isNull())
        {
            failedLoginCount_=std::make_shared<int32_t>(r["failed_login_count"].as<int32_t>());
        }
        if(!r["locked_until"].isNull())
        {
            lockedUntil_=std::make_shared<int64_t>(r["locked_until"].as<int64_t>());
        }
        if(!r["last_failed_login"].isNull())
        {
            lastFailedLogin_=std::make_shared<int64_t>(r["last_failed_login"].as<int64_t>());
        }
        if(!r["org_id"].isNull())
        {
            orgId_=std::make_shared<int32_t>(r["org_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 15 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            username_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            passwordHash_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            salt_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            email_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            publicSub_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            emailVerified_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            mfaEnabled_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            mfaSecret_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            mfaBackupCodes_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            failedLoginCount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            lockedUntil_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            lastFailedLogin_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 14;
        if(!r[index].isNull())
        {
            orgId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Users::Users(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 15)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            username_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            passwordHash_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            salt_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            email_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            publicSub_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            emailVerified_=std::make_shared<bool>(pJson[pMasqueradingVector[7]].asBool());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            mfaEnabled_=std::make_shared<bool>(pJson[pMasqueradingVector[8]].asBool());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            mfaSecret_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            mfaBackupCodes_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            failedLoginCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[11]].asInt64());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            lockedUntil_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[12]].asInt64());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            lastFailedLogin_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[13]].asInt64());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[14]].asInt64());
        }
    }
}

Users::Users(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("username"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["username"].isNull())
        {
            username_=std::make_shared<std::string>(pJson["username"].asString());
        }
    }
    if(pJson.isMember("password_hash"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["password_hash"].isNull())
        {
            passwordHash_=std::make_shared<std::string>(pJson["password_hash"].asString());
        }
    }
    if(pJson.isMember("salt"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["salt"].isNull())
        {
            salt_=std::make_shared<std::string>(pJson["salt"].asString());
        }
    }
    if(pJson.isMember("email"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["email"].isNull())
        {
            email_=std::make_shared<std::string>(pJson["email"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("public_sub"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["public_sub"].isNull())
        {
            publicSub_=std::make_shared<std::string>(pJson["public_sub"].asString());
        }
    }
    if(pJson.isMember("email_verified"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["email_verified"].isNull())
        {
            emailVerified_=std::make_shared<bool>(pJson["email_verified"].asBool());
        }
    }
    if(pJson.isMember("mfa_enabled"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["mfa_enabled"].isNull())
        {
            mfaEnabled_=std::make_shared<bool>(pJson["mfa_enabled"].asBool());
        }
    }
    if(pJson.isMember("mfa_secret"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["mfa_secret"].isNull())
        {
            mfaSecret_=std::make_shared<std::string>(pJson["mfa_secret"].asString());
        }
    }
    if(pJson.isMember("mfa_backup_codes"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["mfa_backup_codes"].isNull())
        {
            mfaBackupCodes_=std::make_shared<std::string>(pJson["mfa_backup_codes"].asString());
        }
    }
    if(pJson.isMember("failed_login_count"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["failed_login_count"].isNull())
        {
            failedLoginCount_=std::make_shared<int32_t>((int32_t)pJson["failed_login_count"].asInt64());
        }
    }
    if(pJson.isMember("locked_until"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["locked_until"].isNull())
        {
            lockedUntil_=std::make_shared<int64_t>((int64_t)pJson["locked_until"].asInt64());
        }
    }
    if(pJson.isMember("last_failed_login"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["last_failed_login"].isNull())
        {
            lastFailedLogin_=std::make_shared<int64_t>((int64_t)pJson["last_failed_login"].asInt64());
        }
    }
    if(pJson.isMember("org_id"))
    {
        dirtyFlag_[14]=true;
        if(!pJson["org_id"].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson["org_id"].asInt64());
        }
    }
}

void Users::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 15)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            username_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            passwordHash_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            salt_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            email_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            publicSub_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            emailVerified_=std::make_shared<bool>(pJson[pMasqueradingVector[7]].asBool());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            mfaEnabled_=std::make_shared<bool>(pJson[pMasqueradingVector[8]].asBool());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            mfaSecret_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            mfaBackupCodes_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            failedLoginCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[11]].asInt64());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            lockedUntil_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[12]].asInt64());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            lastFailedLogin_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[13]].asInt64());
        }
    }
    if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
    {
        dirtyFlag_[14] = true;
        if(!pJson[pMasqueradingVector[14]].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[14]].asInt64());
        }
    }
}

void Users::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("username"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["username"].isNull())
        {
            username_=std::make_shared<std::string>(pJson["username"].asString());
        }
    }
    if(pJson.isMember("password_hash"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["password_hash"].isNull())
        {
            passwordHash_=std::make_shared<std::string>(pJson["password_hash"].asString());
        }
    }
    if(pJson.isMember("salt"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["salt"].isNull())
        {
            salt_=std::make_shared<std::string>(pJson["salt"].asString());
        }
    }
    if(pJson.isMember("email"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["email"].isNull())
        {
            email_=std::make_shared<std::string>(pJson["email"].asString());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("public_sub"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["public_sub"].isNull())
        {
            publicSub_=std::make_shared<std::string>(pJson["public_sub"].asString());
        }
    }
    if(pJson.isMember("email_verified"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["email_verified"].isNull())
        {
            emailVerified_=std::make_shared<bool>(pJson["email_verified"].asBool());
        }
    }
    if(pJson.isMember("mfa_enabled"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["mfa_enabled"].isNull())
        {
            mfaEnabled_=std::make_shared<bool>(pJson["mfa_enabled"].asBool());
        }
    }
    if(pJson.isMember("mfa_secret"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["mfa_secret"].isNull())
        {
            mfaSecret_=std::make_shared<std::string>(pJson["mfa_secret"].asString());
        }
    }
    if(pJson.isMember("mfa_backup_codes"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["mfa_backup_codes"].isNull())
        {
            mfaBackupCodes_=std::make_shared<std::string>(pJson["mfa_backup_codes"].asString());
        }
    }
    if(pJson.isMember("failed_login_count"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["failed_login_count"].isNull())
        {
            failedLoginCount_=std::make_shared<int32_t>((int32_t)pJson["failed_login_count"].asInt64());
        }
    }
    if(pJson.isMember("locked_until"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["locked_until"].isNull())
        {
            lockedUntil_=std::make_shared<int64_t>((int64_t)pJson["locked_until"].asInt64());
        }
    }
    if(pJson.isMember("last_failed_login"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["last_failed_login"].isNull())
        {
            lastFailedLogin_=std::make_shared<int64_t>((int64_t)pJson["last_failed_login"].asInt64());
        }
    }
    if(pJson.isMember("org_id"))
    {
        dirtyFlag_[14] = true;
        if(!pJson["org_id"].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson["org_id"].asInt64());
        }
    }
}

const int32_t &Users::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Users::getId() const noexcept
{
    return id_;
}
void Users::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Users::PrimaryKeyType & Users::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Users::getValueOfUsername() const noexcept
{
    static const std::string defaultValue = std::string();
    if(username_)
        return *username_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Users::getUsername() const noexcept
{
    return username_;
}
void Users::setUsername(const std::string &pUsername) noexcept
{
    username_ = std::make_shared<std::string>(pUsername);
    dirtyFlag_[1] = true;
}
void Users::setUsername(std::string &&pUsername) noexcept
{
    username_ = std::make_shared<std::string>(std::move(pUsername));
    dirtyFlag_[1] = true;
}

const std::string &Users::getValueOfPasswordHash() const noexcept
{
    static const std::string defaultValue = std::string();
    if(passwordHash_)
        return *passwordHash_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Users::getPasswordHash() const noexcept
{
    return passwordHash_;
}
void Users::setPasswordHash(const std::string &pPasswordHash) noexcept
{
    passwordHash_ = std::make_shared<std::string>(pPasswordHash);
    dirtyFlag_[2] = true;
}
void Users::setPasswordHash(std::string &&pPasswordHash) noexcept
{
    passwordHash_ = std::make_shared<std::string>(std::move(pPasswordHash));
    dirtyFlag_[2] = true;
}

const std::string &Users::getValueOfSalt() const noexcept
{
    static const std::string defaultValue = std::string();
    if(salt_)
        return *salt_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Users::getSalt() const noexcept
{
    return salt_;
}
void Users::setSalt(const std::string &pSalt) noexcept
{
    salt_ = std::make_shared<std::string>(pSalt);
    dirtyFlag_[3] = true;
}
void Users::setSalt(std::string &&pSalt) noexcept
{
    salt_ = std::make_shared<std::string>(std::move(pSalt));
    dirtyFlag_[3] = true;
}

const std::string &Users::getValueOfEmail() const noexcept
{
    static const std::string defaultValue = std::string();
    if(email_)
        return *email_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Users::getEmail() const noexcept
{
    return email_;
}
void Users::setEmail(const std::string &pEmail) noexcept
{
    email_ = std::make_shared<std::string>(pEmail);
    dirtyFlag_[4] = true;
}
void Users::setEmail(std::string &&pEmail) noexcept
{
    email_ = std::make_shared<std::string>(std::move(pEmail));
    dirtyFlag_[4] = true;
}
void Users::setEmailToNull() noexcept
{
    email_.reset();
    dirtyFlag_[4] = true;
}

const ::trantor::Date &Users::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &Users::getCreatedAt() const noexcept
{
    return createdAt_;
}
void Users::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[5] = true;
}
void Users::setCreatedAtToNull() noexcept
{
    createdAt_.reset();
    dirtyFlag_[5] = true;
}

const std::string &Users::getValueOfPublicSub() const noexcept
{
    static const std::string defaultValue = std::string();
    if(publicSub_)
        return *publicSub_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Users::getPublicSub() const noexcept
{
    return publicSub_;
}
void Users::setPublicSub(const std::string &pPublicSub) noexcept
{
    publicSub_ = std::make_shared<std::string>(pPublicSub);
    dirtyFlag_[6] = true;
}
void Users::setPublicSub(std::string &&pPublicSub) noexcept
{
    publicSub_ = std::make_shared<std::string>(std::move(pPublicSub));
    dirtyFlag_[6] = true;
}

const bool &Users::getValueOfEmailVerified() const noexcept
{
    static const bool defaultValue = bool();
    if(emailVerified_)
        return *emailVerified_;
    return defaultValue;
}
const std::shared_ptr<bool> &Users::getEmailVerified() const noexcept
{
    return emailVerified_;
}
void Users::setEmailVerified(const bool &pEmailVerified) noexcept
{
    emailVerified_ = std::make_shared<bool>(pEmailVerified);
    dirtyFlag_[7] = true;
}
void Users::setEmailVerifiedToNull() noexcept
{
    emailVerified_.reset();
    dirtyFlag_[7] = true;
}

const bool &Users::getValueOfMfaEnabled() const noexcept
{
    static const bool defaultValue = bool();
    if(mfaEnabled_)
        return *mfaEnabled_;
    return defaultValue;
}
const std::shared_ptr<bool> &Users::getMfaEnabled() const noexcept
{
    return mfaEnabled_;
}
void Users::setMfaEnabled(const bool &pMfaEnabled) noexcept
{
    mfaEnabled_ = std::make_shared<bool>(pMfaEnabled);
    dirtyFlag_[8] = true;
}
void Users::setMfaEnabledToNull() noexcept
{
    mfaEnabled_.reset();
    dirtyFlag_[8] = true;
}

const std::string &Users::getValueOfMfaSecret() const noexcept
{
    static const std::string defaultValue = std::string();
    if(mfaSecret_)
        return *mfaSecret_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Users::getMfaSecret() const noexcept
{
    return mfaSecret_;
}
void Users::setMfaSecret(const std::string &pMfaSecret) noexcept
{
    mfaSecret_ = std::make_shared<std::string>(pMfaSecret);
    dirtyFlag_[9] = true;
}
void Users::setMfaSecret(std::string &&pMfaSecret) noexcept
{
    mfaSecret_ = std::make_shared<std::string>(std::move(pMfaSecret));
    dirtyFlag_[9] = true;
}
void Users::setMfaSecretToNull() noexcept
{
    mfaSecret_.reset();
    dirtyFlag_[9] = true;
}

const std::string &Users::getValueOfMfaBackupCodes() const noexcept
{
    static const std::string defaultValue = std::string();
    if(mfaBackupCodes_)
        return *mfaBackupCodes_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Users::getMfaBackupCodes() const noexcept
{
    return mfaBackupCodes_;
}
void Users::setMfaBackupCodes(const std::string &pMfaBackupCodes) noexcept
{
    mfaBackupCodes_ = std::make_shared<std::string>(pMfaBackupCodes);
    dirtyFlag_[10] = true;
}
void Users::setMfaBackupCodes(std::string &&pMfaBackupCodes) noexcept
{
    mfaBackupCodes_ = std::make_shared<std::string>(std::move(pMfaBackupCodes));
    dirtyFlag_[10] = true;
}
void Users::setMfaBackupCodesToNull() noexcept
{
    mfaBackupCodes_.reset();
    dirtyFlag_[10] = true;
}

const int32_t &Users::getValueOfFailedLoginCount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(failedLoginCount_)
        return *failedLoginCount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Users::getFailedLoginCount() const noexcept
{
    return failedLoginCount_;
}
void Users::setFailedLoginCount(const int32_t &pFailedLoginCount) noexcept
{
    failedLoginCount_ = std::make_shared<int32_t>(pFailedLoginCount);
    dirtyFlag_[11] = true;
}
void Users::setFailedLoginCountToNull() noexcept
{
    failedLoginCount_.reset();
    dirtyFlag_[11] = true;
}

const int64_t &Users::getValueOfLockedUntil() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(lockedUntil_)
        return *lockedUntil_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Users::getLockedUntil() const noexcept
{
    return lockedUntil_;
}
void Users::setLockedUntil(const int64_t &pLockedUntil) noexcept
{
    lockedUntil_ = std::make_shared<int64_t>(pLockedUntil);
    dirtyFlag_[12] = true;
}
void Users::setLockedUntilToNull() noexcept
{
    lockedUntil_.reset();
    dirtyFlag_[12] = true;
}

const int64_t &Users::getValueOfLastFailedLogin() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(lastFailedLogin_)
        return *lastFailedLogin_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Users::getLastFailedLogin() const noexcept
{
    return lastFailedLogin_;
}
void Users::setLastFailedLogin(const int64_t &pLastFailedLogin) noexcept
{
    lastFailedLogin_ = std::make_shared<int64_t>(pLastFailedLogin);
    dirtyFlag_[13] = true;
}
void Users::setLastFailedLoginToNull() noexcept
{
    lastFailedLogin_.reset();
    dirtyFlag_[13] = true;
}

const int32_t &Users::getValueOfOrgId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(orgId_)
        return *orgId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Users::getOrgId() const noexcept
{
    return orgId_;
}
void Users::setOrgId(const int32_t &pOrgId) noexcept
{
    orgId_ = std::make_shared<int32_t>(pOrgId);
    dirtyFlag_[14] = true;
}
void Users::setOrgIdToNull() noexcept
{
    orgId_.reset();
    dirtyFlag_[14] = true;
}

void Users::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Users::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "username",
        "password_hash",
        "salt",
        "email",
        "created_at",
        "public_sub",
        "email_verified",
        "mfa_enabled",
        "mfa_secret",
        "mfa_backup_codes",
        "failed_login_count",
        "locked_until",
        "last_failed_login",
        "org_id"
    };
    return inCols;
}

void Users::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUsername())
        {
            binder << getValueOfUsername();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPasswordHash())
        {
            binder << getValueOfPasswordHash();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSalt())
        {
            binder << getValueOfSalt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getEmail())
        {
            binder << getValueOfEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPublicSub())
        {
            binder << getValueOfPublicSub();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getEmailVerified())
        {
            binder << getValueOfEmailVerified();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getMfaEnabled())
        {
            binder << getValueOfMfaEnabled();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getMfaSecret())
        {
            binder << getValueOfMfaSecret();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getMfaBackupCodes())
        {
            binder << getValueOfMfaBackupCodes();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getFailedLoginCount())
        {
            binder << getValueOfFailedLoginCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getLockedUntil())
        {
            binder << getValueOfLockedUntil();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getLastFailedLogin())
        {
            binder << getValueOfLastFailedLogin();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getOrgId())
        {
            binder << getValueOfOrgId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Users::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    if(dirtyFlag_[14])
    {
        ret.push_back(getColumnName(14));
    }
    return ret;
}

void Users::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getUsername())
        {
            binder << getValueOfUsername();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getPasswordHash())
        {
            binder << getValueOfPasswordHash();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getSalt())
        {
            binder << getValueOfSalt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getEmail())
        {
            binder << getValueOfEmail();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getPublicSub())
        {
            binder << getValueOfPublicSub();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getEmailVerified())
        {
            binder << getValueOfEmailVerified();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getMfaEnabled())
        {
            binder << getValueOfMfaEnabled();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getMfaSecret())
        {
            binder << getValueOfMfaSecret();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getMfaBackupCodes())
        {
            binder << getValueOfMfaBackupCodes();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getFailedLoginCount())
        {
            binder << getValueOfFailedLoginCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getLockedUntil())
        {
            binder << getValueOfLockedUntil();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getLastFailedLogin())
        {
            binder << getValueOfLastFailedLogin();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[14])
    {
        if(getOrgId())
        {
            binder << getValueOfOrgId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Users::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUsername())
    {
        ret["username"]=getValueOfUsername();
    }
    else
    {
        ret["username"]=Json::Value();
    }
    if(getPasswordHash())
    {
        ret["password_hash"]=getValueOfPasswordHash();
    }
    else
    {
        ret["password_hash"]=Json::Value();
    }
    if(getSalt())
    {
        ret["salt"]=getValueOfSalt();
    }
    else
    {
        ret["salt"]=Json::Value();
    }
    if(getEmail())
    {
        ret["email"]=getValueOfEmail();
    }
    else
    {
        ret["email"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getPublicSub())
    {
        ret["public_sub"]=getValueOfPublicSub();
    }
    else
    {
        ret["public_sub"]=Json::Value();
    }
    if(getEmailVerified())
    {
        ret["email_verified"]=getValueOfEmailVerified();
    }
    else
    {
        ret["email_verified"]=Json::Value();
    }
    if(getMfaEnabled())
    {
        ret["mfa_enabled"]=getValueOfMfaEnabled();
    }
    else
    {
        ret["mfa_enabled"]=Json::Value();
    }
    if(getMfaSecret())
    {
        ret["mfa_secret"]=getValueOfMfaSecret();
    }
    else
    {
        ret["mfa_secret"]=Json::Value();
    }
    if(getMfaBackupCodes())
    {
        ret["mfa_backup_codes"]=getValueOfMfaBackupCodes();
    }
    else
    {
        ret["mfa_backup_codes"]=Json::Value();
    }
    if(getFailedLoginCount())
    {
        ret["failed_login_count"]=getValueOfFailedLoginCount();
    }
    else
    {
        ret["failed_login_count"]=Json::Value();
    }
    if(getLockedUntil())
    {
        ret["locked_until"]=(Json::Int64)getValueOfLockedUntil();
    }
    else
    {
        ret["locked_until"]=Json::Value();
    }
    if(getLastFailedLogin())
    {
        ret["last_failed_login"]=(Json::Int64)getValueOfLastFailedLogin();
    }
    else
    {
        ret["last_failed_login"]=Json::Value();
    }
    if(getOrgId())
    {
        ret["org_id"]=getValueOfOrgId();
    }
    else
    {
        ret["org_id"]=Json::Value();
    }
    return ret;
}

std::string Users::toString() const
{
    return toJson().toStyledString();
}

Json::Value Users::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 15)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getUsername())
            {
                ret[pMasqueradingVector[1]]=getValueOfUsername();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getPasswordHash())
            {
                ret[pMasqueradingVector[2]]=getValueOfPasswordHash();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getSalt())
            {
                ret[pMasqueradingVector[3]]=getValueOfSalt();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getEmail())
            {
                ret[pMasqueradingVector[4]]=getValueOfEmail();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[5]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getPublicSub())
            {
                ret[pMasqueradingVector[6]]=getValueOfPublicSub();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getEmailVerified())
            {
                ret[pMasqueradingVector[7]]=getValueOfEmailVerified();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getMfaEnabled())
            {
                ret[pMasqueradingVector[8]]=getValueOfMfaEnabled();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getMfaSecret())
            {
                ret[pMasqueradingVector[9]]=getValueOfMfaSecret();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getMfaBackupCodes())
            {
                ret[pMasqueradingVector[10]]=getValueOfMfaBackupCodes();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getFailedLoginCount())
            {
                ret[pMasqueradingVector[11]]=getValueOfFailedLoginCount();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getLockedUntil())
            {
                ret[pMasqueradingVector[12]]=(Json::Int64)getValueOfLockedUntil();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getLastFailedLogin())
            {
                ret[pMasqueradingVector[13]]=(Json::Int64)getValueOfLastFailedLogin();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[14].empty())
        {
            if(getOrgId())
            {
                ret[pMasqueradingVector[14]]=getValueOfOrgId();
            }
            else
            {
                ret[pMasqueradingVector[14]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getUsername())
    {
        ret["username"]=getValueOfUsername();
    }
    else
    {
        ret["username"]=Json::Value();
    }
    if(getPasswordHash())
    {
        ret["password_hash"]=getValueOfPasswordHash();
    }
    else
    {
        ret["password_hash"]=Json::Value();
    }
    if(getSalt())
    {
        ret["salt"]=getValueOfSalt();
    }
    else
    {
        ret["salt"]=Json::Value();
    }
    if(getEmail())
    {
        ret["email"]=getValueOfEmail();
    }
    else
    {
        ret["email"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getPublicSub())
    {
        ret["public_sub"]=getValueOfPublicSub();
    }
    else
    {
        ret["public_sub"]=Json::Value();
    }
    if(getEmailVerified())
    {
        ret["email_verified"]=getValueOfEmailVerified();
    }
    else
    {
        ret["email_verified"]=Json::Value();
    }
    if(getMfaEnabled())
    {
        ret["mfa_enabled"]=getValueOfMfaEnabled();
    }
    else
    {
        ret["mfa_enabled"]=Json::Value();
    }
    if(getMfaSecret())
    {
        ret["mfa_secret"]=getValueOfMfaSecret();
    }
    else
    {
        ret["mfa_secret"]=Json::Value();
    }
    if(getMfaBackupCodes())
    {
        ret["mfa_backup_codes"]=getValueOfMfaBackupCodes();
    }
    else
    {
        ret["mfa_backup_codes"]=Json::Value();
    }
    if(getFailedLoginCount())
    {
        ret["failed_login_count"]=getValueOfFailedLoginCount();
    }
    else
    {
        ret["failed_login_count"]=Json::Value();
    }
    if(getLockedUntil())
    {
        ret["locked_until"]=(Json::Int64)getValueOfLockedUntil();
    }
    else
    {
        ret["locked_until"]=Json::Value();
    }
    if(getLastFailedLogin())
    {
        ret["last_failed_login"]=(Json::Int64)getValueOfLastFailedLogin();
    }
    else
    {
        ret["last_failed_login"]=Json::Value();
    }
    if(getOrgId())
    {
        ret["org_id"]=getValueOfOrgId();
    }
    else
    {
        ret["org_id"]=Json::Value();
    }
    return ret;
}

bool Users::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("username"))
    {
        if(!validJsonOfField(1, "username", pJson["username"], err, true))
            return false;
    }
    else
    {
        err="The username column cannot be null";
        return false;
    }
    if(pJson.isMember("password_hash"))
    {
        if(!validJsonOfField(2, "password_hash", pJson["password_hash"], err, true))
            return false;
    }
    else
    {
        err="The password_hash column cannot be null";
        return false;
    }
    if(pJson.isMember("salt"))
    {
        if(!validJsonOfField(3, "salt", pJson["salt"], err, true))
            return false;
    }
    else
    {
        err="The salt column cannot be null";
        return false;
    }
    if(pJson.isMember("email"))
    {
        if(!validJsonOfField(4, "email", pJson["email"], err, true))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(5, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("public_sub"))
    {
        if(!validJsonOfField(6, "public_sub", pJson["public_sub"], err, true))
            return false;
    }
    if(pJson.isMember("email_verified"))
    {
        if(!validJsonOfField(7, "email_verified", pJson["email_verified"], err, true))
            return false;
    }
    if(pJson.isMember("mfa_enabled"))
    {
        if(!validJsonOfField(8, "mfa_enabled", pJson["mfa_enabled"], err, true))
            return false;
    }
    if(pJson.isMember("mfa_secret"))
    {
        if(!validJsonOfField(9, "mfa_secret", pJson["mfa_secret"], err, true))
            return false;
    }
    if(pJson.isMember("mfa_backup_codes"))
    {
        if(!validJsonOfField(10, "mfa_backup_codes", pJson["mfa_backup_codes"], err, true))
            return false;
    }
    if(pJson.isMember("failed_login_count"))
    {
        if(!validJsonOfField(11, "failed_login_count", pJson["failed_login_count"], err, true))
            return false;
    }
    if(pJson.isMember("locked_until"))
    {
        if(!validJsonOfField(12, "locked_until", pJson["locked_until"], err, true))
            return false;
    }
    if(pJson.isMember("last_failed_login"))
    {
        if(!validJsonOfField(13, "last_failed_login", pJson["last_failed_login"], err, true))
            return false;
    }
    if(pJson.isMember("org_id"))
    {
        if(!validJsonOfField(14, "org_id", pJson["org_id"], err, true))
            return false;
    }
    return true;
}
bool Users::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err)
{
    if(pMasqueradingVector.size() != 15)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[14].empty())
      {
          if(pJson.isMember(pMasqueradingVector[14]))
          {
              if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Users::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("username"))
    {
        if(!validJsonOfField(1, "username", pJson["username"], err, false))
            return false;
    }
    if(pJson.isMember("password_hash"))
    {
        if(!validJsonOfField(2, "password_hash", pJson["password_hash"], err, false))
            return false;
    }
    if(pJson.isMember("salt"))
    {
        if(!validJsonOfField(3, "salt", pJson["salt"], err, false))
            return false;
    }
    if(pJson.isMember("email"))
    {
        if(!validJsonOfField(4, "email", pJson["email"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(5, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("public_sub"))
    {
        if(!validJsonOfField(6, "public_sub", pJson["public_sub"], err, false))
            return false;
    }
    if(pJson.isMember("email_verified"))
    {
        if(!validJsonOfField(7, "email_verified", pJson["email_verified"], err, false))
            return false;
    }
    if(pJson.isMember("mfa_enabled"))
    {
        if(!validJsonOfField(8, "mfa_enabled", pJson["mfa_enabled"], err, false))
            return false;
    }
    if(pJson.isMember("mfa_secret"))
    {
        if(!validJsonOfField(9, "mfa_secret", pJson["mfa_secret"], err, false))
            return false;
    }
    if(pJson.isMember("mfa_backup_codes"))
    {
        if(!validJsonOfField(10, "mfa_backup_codes", pJson["mfa_backup_codes"], err, false))
            return false;
    }
    if(pJson.isMember("failed_login_count"))
    {
        if(!validJsonOfField(11, "failed_login_count", pJson["failed_login_count"], err, false))
            return false;
    }
    if(pJson.isMember("locked_until"))
    {
        if(!validJsonOfField(12, "locked_until", pJson["locked_until"], err, false))
            return false;
    }
    if(pJson.isMember("last_failed_login"))
    {
        if(!validJsonOfField(13, "last_failed_login", pJson["last_failed_login"], err, false))
            return false;
    }
    if(pJson.isMember("org_id"))
    {
        if(!validJsonOfField(14, "org_id", pJson["org_id"], err, false))
            return false;
    }
    return true;
}
bool Users::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                             const std::vector<std::string> &pMasqueradingVector,
                                             std::string &err)
{
    if(pMasqueradingVector.size() != 15)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
      if(!pMasqueradingVector[14].empty() && pJson.isMember(pMasqueradingVector[14]))
      {
          if(!validJsonOfField(14, pMasqueradingVector[14], pJson[pMasqueradingVector[14]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Users::validJsonOfField(size_t index,
                             const std::string &fieldName,
                             const Json::Value &pJson,
                             std::string &err,
                             bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 256)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 256)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 36)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 36)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && drogon::utils::utf8Length(pJson.asCString()) > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 14:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
std::vector<Oauth2AccessTokens> Users::getAccessTokens(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from oauth2_access_tokens where user_id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *id_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<Oauth2AccessTokens> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(Oauth2AccessTokens(row));
    }
    return ret;
}

void Users::getAccessTokens(const DbClientPtr &clientPtr,
                            const std::function<void(std::vector<Oauth2AccessTokens>)> &rcb,
                            const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from oauth2_access_tokens where user_id = $1";
    *clientPtr << sql
               << *id_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<Oauth2AccessTokens> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(Oauth2AccessTokens(row));
                   }
                   rcb(ret);
               }
               >> ecb;
}
std::vector<std::pair<Roles,UserRoles>> Users::getRole(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from roles,user_roles where user_roles.user_id = $1 and user_roles.role_id = roles.id";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *id_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<std::pair<Roles,UserRoles>> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(std::pair<Roles,UserRoles>(
            Roles(row),UserRoles(row,Roles::getColumnNumber())));
    }
    return ret;
}

void Users::getRole(const DbClientPtr &clientPtr,
                    const std::function<void(std::vector<std::pair<Roles,UserRoles>>)> &rcb,
                    const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from roles,user_roles where user_roles.user_id = $1 and user_roles.role_id = roles.id";
    *clientPtr << sql
               << *id_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<std::pair<Roles,UserRoles>> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(std::pair<Roles,UserRoles>(
                           Roles(row),UserRoles(row,Roles::getColumnNumber())));
                   }
                   rcb(ret);
               }
               >> ecb;
}
std::vector<Oauth2UserConsents> Users::getUserConsents(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from oauth2_user_consents where internal_user_id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *id_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<Oauth2UserConsents> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(Oauth2UserConsents(row));
    }
    return ret;
}

void Users::getUserConsents(const DbClientPtr &clientPtr,
                            const std::function<void(std::vector<Oauth2UserConsents>)> &rcb,
                            const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from oauth2_user_consents where internal_user_id = $1";
    *clientPtr << sql
               << *id_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<Oauth2UserConsents> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(Oauth2UserConsents(row));
                   }
                   rcb(ret);
               }
               >> ecb;
}
std::vector<Oauth2SubjectMappings> Users::getSubjectMappings(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from oauth2_subject_mappings where internal_user_id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *id_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    std::vector<Oauth2SubjectMappings> ret;
    ret.reserve(r.size());
    for (auto const &row : r)
    {
        ret.emplace_back(Oauth2SubjectMappings(row));
    }
    return ret;
}

void Users::getSubjectMappings(const DbClientPtr &clientPtr,
                               const std::function<void(std::vector<Oauth2SubjectMappings>)> &rcb,
                               const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from oauth2_subject_mappings where internal_user_id = $1";
    *clientPtr << sql
               << *id_
               >> [rcb = std::move(rcb)](const Result &r){
                   std::vector<Oauth2SubjectMappings> ret;
                   ret.reserve(r.size());
                   for (auto const &row : r)
                   {
                       ret.emplace_back(Oauth2SubjectMappings(row));
                   }
                   rcb(ret);
               }
               >> ecb;
}
Organizations Users::getOrganizations(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from organizations where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *orgId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Organizations(r[0]);
}

void Users::getOrganizations(const DbClientPtr &clientPtr,
                             const std::function<void(Organizations)> &rcb,
                             const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from organizations where id = $1";
    *clientPtr << sql
               << *orgId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Organizations(r[0]));
                    }
               }
               >> ecb;
}
